# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 11:10

from django.db import migrations, models

#Fix integrity error in imported Person.sexkey sometimes being zero
def update_sex(apps,schema_editor):
    schema_editor.execute("update pbw.Person set sexKey=1 where sexKey=0")



class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_sex)
    ]
