# Generated by Django 3.2.25 on 2024-09-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='factoidtype',
            field=models.ForeignKey(blank=True, db_column='factoidTypeKey', null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.factoidtype'),
        ),
        migrations.AlterField(
            model_name='famnamefactoid',
            name='familyname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.familyname'),
        ),
    ]
