# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 13:30
from __future__ import unicode_literals

from django.db import migrations

#This migration fixes the factoid subtables by removing their joint primary keys
#and creating a normal auto_increment id

def update_factoid_primary_keys(apps,schema_editor):
    factoidTables=["DeathFactoid","FamNameFactoid","OccupationFactoid",
                   "KinFactoid","DignityFactoid","EthnicityFactoid","ActivityFactoid",
                   "FactoidLocation","FamNameFactoid",
                   "PossessionFactoid","ReligionFactoid","VNameFactoid"]
    for f in factoidTables:
        schema_editor.execute("alter table "+f+" modify factoidKey int;")
        schema_editor.execute("alter table "+f+" drop primary key;")
        schema_editor.execute("alter table "+f+" ADD COLUMN id int(11) AUTO_INCREMENT primary key FIRST;")


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0002_fix_sex_key'),
    ]


#
    operations = [
        #migrations.RunPython(update_factoid_primary_keys)
    ]
