# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 08:21
from __future__ import unicode_literals

from django.db import migrations,models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0005_auto_20161004_1721'),
    ]

    operations = [


        migrations.AddField(
            model_name='dignityfactoid',
            name='dignityoffice',
            field=models.ForeignKey(db_column='dignityoffice', blank=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Dignityoffice'),
        ),


    ]
