# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 09:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0007_auto_20161005_1023'),
    ]

    operations = [
        migrations.RunSQL('update DignityFactoid set dignityoffice=doKey;'),
        migrations.RunSQL('update DignityFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update EthnicityFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update EthnicityFactoid set ethnicity_id=ethnicityKey;'),

        migrations.RunSQL('update Factoid set factoidtype_id=factoidTypeKey;'),
        migrations.RunSQL('update Factoid set source_id=sourceKey;'),
        migrations.RunSQL('update FactoidLocation set factoid_id=factoidKey;'),
        migrations.RunSQL('update FactoidLocation set location_id=locationKey;'),
        migrations.RunSQL('update FactoidPerson set factoid_id=factoidKey;'),
        migrations.RunSQL('update FactoidPerson set factoidpersontype_id=fpTypeKey;'),
        migrations.RunSQL('update KinFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update KinFactoid set kinship_id=kinKey;'),
        migrations.RunSQL('update LangFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update LangFactoid set languageskill_id=langKey;'),
        migrations.RunSQL('update OccupationFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update OccupationFactoid set occupation_id=occupationKey;'),
        migrations.RunSQL('update Person set sex_id=sexKey;'),
        migrations.RunSQL('update ReligionFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update ReligionFactoid set religion_id=religionKey;'),
        migrations.RunSQL('update VNameFactoid set factoid_id=factoidKey;'),
        migrations.RunSQL('update VNameFactoid set variantname_id=vnameKey;')
    ]
