# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 10:35


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0008_copy_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dignityfactoid',
            name='dignityoffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbw.Dignityoffice'),
        ),
        migrations.AlterField(
            model_name='dignityfactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='ethnicityfactoid',
            name='ethnicity',
            field=models.ForeignKey(db_column='ethnicityKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Ethnicity'),
        ),
        migrations.AlterField(
            model_name='ethnicityfactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='factoidtype',
            field=models.ForeignKey(db_column='factoidTypeKey', default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoidtype'),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='source',
            field=models.ForeignKey(db_column='sourceKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Source'),
        ),
        migrations.AlterField(
            model_name='factoidlocation',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='factoidlocation',
            name='location',
            field=models.ForeignKey(db_column='locationKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Location'),
        ),
        migrations.AlterField(
            model_name='factoidperson',
            name='factoid',
            field=models.ForeignKey(db_column='factoidkey', default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='factoidperson',
            name='factoidpersontype',
            field=models.ForeignKey(db_column='fpTypeKey', default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoidpersontype'),
        ),
        migrations.AlterField(
            model_name='factoidperson',
            name='person',
            field=models.ForeignKey(db_column='personKey', default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Person'),
        ),
        migrations.AlterField(
            model_name='kinfactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoid_id', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='kinfactoid',
            name='kinship',
            field=models.ForeignKey(db_column='kinKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Kinshiptype'),
        ),
        migrations.AlterField(
            model_name='langfactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='langfactoid',
            name='languageskill',
            field=models.ForeignKey(db_column='langkey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Languageskill'),
        ),
        migrations.AlterField(
            model_name='occupationfactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='occupationfactoid',
            name='occupation',
            field=models.ForeignKey(db_column='OccupationKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Occupation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.ForeignKey(db_column='sexKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Sexauth'),
        ),
        migrations.AlterField(
            model_name='religionfactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='religionfactoid',
            name='religion',
            field=models.ForeignKey(db_column='religionKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Religion'),
        ),
        migrations.AlterField(
            model_name='vnamefactoid',
            name='factoid',
            field=models.ForeignKey(db_column='factoidKey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
        migrations.AlterField(
            model_name='vnamefactoid',
            name='variantname',
            field=models.ForeignKey(db_column='vnamekey', on_delete=django.db.models.deletion.CASCADE, to='pbw.Variantname'),
        ),
        migrations.AlterUniqueTogether(
            name='dvsqlindxattr',
            unique_together=set([('indexkey', 'attrkey')]),
        ),
        migrations.AlterUniqueTogether(
            name='narrativefactoid',
            unique_together=set([('factoidkey', 'narrativeunitid')]),
        ),
    ]
