# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 15:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0011_indexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoidtype',
            name='orderno',
            field=models.IntegerField(default=99),
        ),
    ]
