# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 17:05


from django.db import migrations, models
import django.db.models.deletion

#
class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0012_factoidtype_orderno'),
    ]




    operations = [
        migrations.RenameField(
            model_name='published',
            old_name='boulloterionkey',
            new_name='boulloterionKey',
        ),
        migrations.RenameField(
            model_name='seal',
            old_name='collectionkey',
            new_name='collectionKey',
        ),
        migrations.AddField(
            model_name='published',
            name='bibliography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Bibliography'),
        ),
        migrations.AddField(
            model_name='published',
            name='boulloterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Boulloterion'),
        ),
        migrations.AddField(
            model_name='seal',
            name='boulloterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Boulloterion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seal',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='boulloterionkey',
            field=models.IntegerField(db_column='boulloterionKey'),
        ),
    ]
