# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 17:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0013_auto_20161201_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published',
            name='bibliography',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Bibliography'),
        ),
        migrations.AlterField(
            model_name='published',
            name='boulloterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Boulloterion'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='boulloterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Boulloterion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seal',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Collection'),
            preserve_default=False,
        ),
    ]
