# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 11:34


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0015_auto_20161201_1723'),
    ]



    operations = [


    ]
