# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0016_scdate_factoid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'ordering': ['latinbib']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['sourceid']},
        ),
        # migrations.AddField(
        #     model_name='scdate',
        #     name='factoid',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        # ),
    ]
