# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0020_auto_20170130_1638'),
    ]


    operations = [
        migrations.RunSQL(["update FamNameFactoid set factoid_id=factoidKey where factoidKey > 0"]),
        migrations.RunSQL(["update FamNameFactoid set familyname_id=famNameKey where famNameKey > 0"])
    ]
