# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 17:11

from pbw.models import Kinshiptype

from django.db import migrations
import re

# Son/daughter of
# Brother/sister of
# Husband/wife of
# Brother in law/Sister in law of
# Nephew/niece of
# uncle, aunt of
# cousin of

def set_kinorder(apps, schema_editor):
    KinshipType = apps.get_model("pbw", "Kinshiptype")    
    for kin in Kinshiptype.objects.all():
    	if re.search("^Son$|^daughter$", kin.gspecrelat, re.I):
    		kinorder=1
    	elif re.search("^brother$|sister$", kin.gspecrelat, re.I):
    		kinorder=2
    	elif re.search("^husband$|^wife$", kin.gspecrelat, re.I):
			kinorder=3
    	elif re.search("^brother\-in\-law$|^sister\-in\-law$", kin.gspecrelat, re.I):
    		kinorder=4
    	elif re.search("^nephew$|^niece$", kin.gspecrelat, re.I):
    		kinorder=5
    	elif re.search("^uncle|aunt$", kin.gspecrelat, re.I):
    		kinorder=6
    	elif re.search("^cousin$", kin.gspecrelat, re.I):
    		kinorder=7
    	else:
    		kinorder=99
    	kin.kinorder=kinorder
    	kin.save()   		




class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0022_kinshiptype_kinorder'),
    ]

    operations = [
    	migrations.RunPython(set_kinorder),
    ]
