# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 11:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0023_auto_20170130_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'ordering': ['ethname']},
        ),
        migrations.AlterModelOptions(
            name='kinshiptype',
            options={'ordering': ['kinorder', 'gspecrelat']},
        ),
        migrations.AlterModelOptions(
            name='scdate',
            options={'ordering': ['year', 'yrorder']},
        ),
    ]
