# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0024_auto_20170222_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='possessionfactoid',
            name='factoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
    ]
