# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 12:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0026_auto_20170222_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possessionfactoid',
            options={'ordering': ['possessionname']},
        ),
    ]
