# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-25 10:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0027_auto_20170222_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geonames_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pleiades_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='origldesc',
            field=models.TextField(blank=True, db_column='origLDesc'),
        ),
        migrations.AlterField(
            model_name='person',
            name='floruit',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='nameol',
            field=models.CharField(blank=True, db_column='nameOL', max_length=100),
        ),
    ]
