# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 15:41


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pbw', '0028_add_pleides_geonames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dignityoffice',
            options={'ordering': ['stdname']},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['occupationname']},
        ),
        migrations.AlterField(
            model_name='factoid',
            name='source',
            field=models.ForeignKey(blank=True, db_column='sourceKey', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pbw.Source'),
        ),
    ]
