# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 15:48


from django.db import migrations, models

def remove_sources(apps, schema_editor):
    Factoid = apps.get_model("pbw", "Factoid")
    uncertain_factoids = Factoid.objects.filter(factoidtype__id=18)
    for uncertain in uncertain_factoids:
        uncertain.sourceref=''
        uncertain.source = None
        uncertain.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0029_alter_factoid_source'),
    ]

    operations = [
        migrations.RunPython(remove_sources),
    ]

