# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0030_remove_uncertain_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='scdate',
            name='certainty',
            field=models.IntegerField(default=1),
        ),
    ]
