# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 12:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0031_scdate_certainty'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativefactoid',
            name='factoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Factoid'),
        ),
    ]
