# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0032_narrativefactoid_factoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativefactoid',
            name='narrativeunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbw.Narrativeunit'),
        ),
    ]
