# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0033_narrativefactoid_narrativeunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativefactoid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='narrativefactoid',
            unique_together=set([]),
        ),
    ]
