# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist

def populate_narrative_factoids(apps, schema_editor):
    NarrativeFactoid = apps.get_model("pbw", "Narrativefactoid")
    Factoid = apps.get_model("pbw", "Factoid")
    Narrativeunit = apps.get_model("pbw", "Narrativeunit")
    for nf in NarrativeFactoid.objects.all():
        try:
            factoid = Factoid.objects.get(id=nf.factoidkey)
            nf.factoid=factoid
            nunit = Narrativeunit.objects.get(narrativeunitid=nf.narrativeunitid)
            nf.narrativeunit=nunit
            nf.save()
        except ObjectDoesNotExist:
            print ('missing objects for:{}'.format(nf.id))

class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0034_add_narrative_factoid_id'),
    ]

    operations = [
        migrations.RunPython(populate_narrative_factoids),
    ]
