# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 16:15
from __future__ import unicode_literals
import re
from django.db import migrations

def add_year_order(apps, schema_editor):
    Narrativeunit = apps.get_model("pbw", "Narrativeunit")
    # Only populate units attached to factoids
    for nunit in Narrativeunit.objects.filter(narrativefactoid__isnull=False):
        if nunit.dates and len(nunit.dates) > 0:
            #find year in text
            m= re.search('^([0-9]+)',nunit.dates)
            if m:
                year = m.group(1)
                nunit.yearorder = year
                nunit.save()



class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0036_narrativeunit_yearorder'),
    ]

    operations = [
        migrations.RunPython(add_year_order),
    ]
