# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0037_populate_year_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='scdate',
            name='datetype',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='pbw.Datetypes'),
        ),
    ]
