# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-10 14:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0040_narrativeunit_factoids'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='factoids',
            field=models.ManyToManyField(related_name='persons', through='pbw.Factoidperson', to='pbw.Factoid'),
        ),
    ]
