# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0041_person_factoids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativefactoid',
            name='factoidkey',
            field=models.IntegerField(db_column='factoidKey', null=True),
        ),
        migrations.AlterField(
            model_name='narrativefactoid',
            name='fmkey',
            field=models.IntegerField(db_column='fmKey', null=True),
        ),
        migrations.AlterField(
            model_name='narrativefactoid',
            name='hide',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='narrativefactoid',
            name='narrativeunitid',
            field=models.IntegerField(db_column='narrativeUnitID', null=True),
        ),
    ]
