# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0042_null_narrativefactoidkey_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
