# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0044_seal_link_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['collectionname']},
        ),
    ]
