# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-07 15:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0045_collection_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boulloterion',
            options={'ordering': ['title']},
        ),
    ]
