# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-08 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0046_boulloterion_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['locname']},
        ),
    ]
