# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-21 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0049_factoid_boulloterion'),
    ]

    operations = [
        migrations.RunSQL(["alter table Bibliography modify column latinBib longtext CHARACTER SET utf8;"]),
        migrations.RunSQL(["alter table Bibliography modify column shortName text CHARACTER SET utf8;"]),
        migrations.RunSQL(["alter table Collection modify column collectionName text CHARACTER SET utf8;"]),
        migrations.RunSQL(["alter table Collection modify column shortName text CHARACTER SET utf8;"])
    ]
