# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 14:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0052_auto_20170627_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='in_2011',
            field=models.BooleanField(default=False),
        ),
    ]
