# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-24 13:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbw', '0054_hierarchyunit_narrativeunit'),
    ]

    operations = [
        migrations.RunSQL(["update HierarchyUnit set narrativeunit_id=narrativeUnitID"])
    ]
